#ifndef RFIDCARDREADERDLL2_GLOBAL_H
#define RFIDCARDREADERDLL2_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RFIDCARDREADERDLL2_LIBRARY)
#  define RFIDCARDREADERDLL2_EXPORT Q_DECL_EXPORT
#else
#  define RFIDCARDREADERDLL2_EXPORT Q_DECL_IMPORT
#endif

#endif // RFIDCARDREADERDLL2_GLOBAL_H
